global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq.Expressions;
global using Ardalis.GuardClauses;
global using ClinicManagement.ApplicationCore.Entities;
global using ClinicManagement.ApplicationCore.Models.Requests;
global using ClinicManagement.ApplicationCore.Models.Responses;
global using MedicApp.SharedKernel;
global using MedicApp.SharedKernel.Interfaces;
global using Newtonsoft.Json.Linq;
