global using System.ComponentModel.DataAnnotations;
global using ClinicManagement.WebApp;
global using ClinicManagement.WebApp.Components;
global using ClinicManagement.WebApp.Models;
global using MedicApp.SharedKernel;
global using MedicApp.SharedServices.Api;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
